//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtTracker.Resources.UserAccount {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NtTracker.Resources.UserAccount.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AccountStatus {
            get {
                return ResourceManager.GetString("AccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is currently locked. You may unlock it manually or, if it has an unlock date, wait for it to unlock automatically..
        /// </summary>
        public static string AdminLocked {
            get {
                return ResourceManager.GetString("AdminLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are already registered click here to login..
        /// </summary>
        public static string AlreadyRegistered {
            get {
                return ResourceManager.GetString("AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication server error.
        /// </summary>
        public static string AuthenticationError {
            get {
                return ResourceManager.GetString("AuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic data.
        /// </summary>
        public static string BasicData {
            get {
                return ResourceManager.GetString("BasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the information related to this account will be irreversibly removed from the system. Are you sure you want to delete this user account?.
        /// </summary>
        public static string DeleteDescription {
            get {
                return ResourceManager.GetString("DeleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed login attempts.
        /// </summary>
        public static string FailedAttempts {
            get {
                return ResourceManager.GetString("FailedAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is administrator?.
        /// </summary>
        public static string IsAdmin {
            get {
                return ResourceManager.GetString("IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful. You can now use your account to log in to the system..
        /// </summary>
        public static string JustRegistered {
            get {
                return ResourceManager.GetString("JustRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login.
        /// </summary>
        public static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login data.
        /// </summary>
        public static string LastLoginData {
            get {
                return ResourceManager.GetString("LastLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address and user agent of the last login.
        /// </summary>
        public static string LastLoginData_Desc {
            get {
                return ResourceManager.GetString("LastLoginData_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection data.
        /// </summary>
        public static string LastLoginInfo {
            get {
                return ResourceManager.GetString("LastLoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock account.
        /// </summary>
        public static string LockAccount {
            get {
                return ResourceManager.GetString("LockAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account lock data.
        /// </summary>
        public static string LockData {
            get {
                return ResourceManager.GetString("LockData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account will be locked and the user will not be able to log in to the system until it&apos;s unlocked again. Are you sure you want to lock this account?.
        /// </summary>
        public static string LockDescription {
            get {
                return ResourceManager.GetString("LockDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a DMSAS/SSPA Intranet account to log in the system. You must have registered previously to log in..
        /// </summary>
        public static string LoginDescription {
            get {
                return ResourceManager.GetString("LoginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format for the user name is surname-name-ID ending, e.g. smithjohn61E..
        /// </summary>
        public static string LoginDescription2 {
            get {
                return ResourceManager.GetString("LoginDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect user name or password..
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have problems to login or register, please contact your IT service..
        /// </summary>
        public static string LoginHelp {
            get {
                return ResourceManager.GetString("LoginHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been temporarily locked after too many failed login attempts. It will unlock .
        /// </summary>
        public static string LoginLocked {
            get {
                return ResourceManager.GetString("LoginLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Further login tries will increase the lockout time or will end up locking the account indefinitely..
        /// </summary>
        public static string LoginLocked2 {
            get {
                return ResourceManager.GetString("LoginLocked2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been indefinitely locked. Contact an administrator of the system to have it unlocked..
        /// </summary>
        public static string LoginLockedPerm {
            get {
                return ResourceManager.GetString("LoginLockedPerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as new user.
        /// </summary>
        public static string RegisterDesc {
            get {
                return ResourceManager.GetString("RegisterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a new user using a DMSAS/SSPA intranet account..
        /// </summary>
        public static string RegisterDescription {
            get {
                return ResourceManager.GetString("RegisterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This new user account is specific for this application but it&apos;s linked to the SSPA Intranet for authentication. Therefore you need an already existing DMSAS/SSPA Intranet user to register..
        /// </summary>
        public static string RegisterDescription2 {
            get {
                return ResourceManager.GetString("RegisterDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered from.
        /// </summary>
        public static string RegisteredFrom {
            get {
                return ResourceManager.GetString("RegisteredFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string RegisteredTo {
            get {
                return ResourceManager.GetString("RegisteredTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user registration.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration date.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Status_Locked {
            get {
                return ResourceManager.GetString("Status_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Status_Normal {
            get {
                return ResourceManager.GetString("Status_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Type_Admin {
            get {
                return ResourceManager.GetString("Type_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal user.
        /// </summary>
        public static string Type_Normal {
            get {
                return ResourceManager.GetString("Type_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock account.
        /// </summary>
        public static string UnlockAccount {
            get {
                return ResourceManager.GetString("UnlockAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock date.
        /// </summary>
        public static string UnlockDate {
            get {
                return ResourceManager.GetString("UnlockDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account will be unlocked and the user will be able to log in to the system again. Are you sure you want to unlock this account?.
        /// </summary>
        public static string UnlockDescription {
            get {
                return ResourceManager.GetString("UnlockDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identified as.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a user account with that name..
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter accounts.
        /// </summary>
        public static string UserFilter {
            get {
                return ResourceManager.GetString("UserFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity history.
        /// </summary>
        public static string UserOperations {
            get {
                return ResourceManager.GetString("UserOperations", resourceCulture);
            }
        }
    }
}
