//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtTracker.Resources.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NtTracker.Resources.Shared.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string AdminIndex {
            get {
                return ResourceManager.GetString("AdminIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From the administration section you can see information about the usage of the application and control the operations performed by the users in the system..
        /// </summary>
        public static string AdministrationSection {
            get {
                return ResourceManager.GetString("AdministrationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation log.
        /// </summary>
        public static string AdminOperations {
            get {
                return ResourceManager.GetString("AdminOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this section you can see a list of all the operations performed by the users in the system, detailed both by the users that performed them and the patients affected..
        /// </summary>
        public static string AdminOperationsDesc {
            get {
                return ResourceManager.GetString("AdminOperationsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration panel.
        /// </summary>
        public static string AdminPanel {
            get {
                return ResourceManager.GetString("AdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User accounts.
        /// </summary>
        public static string AdminUsers {
            get {
                return ResourceManager.GetString("AdminUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this section you can see a list of all the users registered in the system, you can see their information, delete them, unlock locked accounts or search the operations performed by them in the system..
        /// </summary>
        public static string AdminUsersDesc {
            get {
                return ResourceManager.GetString("AdminUsersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aEEG.
        /// </summary>
        public static string AEEG {
            get {
                return ResourceManager.GetString("AEEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burst supression.
        /// </summary>
        public static string AEEG_BurstSupression {
            get {
                return ResourceManager.GetString("AEEG_BurstSupression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous.
        /// </summary>
        public static string AEEG_Continuous {
            get {
                return ResourceManager.GetString("AEEG_Continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convulsion.
        /// </summary>
        public static string AEEG_Convulsion {
            get {
                return ResourceManager.GetString("AEEG_Convulsion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinuous.
        /// </summary>
        public static string AEEG_Discontinuous {
            get {
                return ResourceManager.GetString("AEEG_Discontinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat.
        /// </summary>
        public static string AEEG_Flat {
            get {
                return ResourceManager.GetString("AEEG_Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low voltage.
        /// </summary>
        public static string AEEG_LowVoltage {
            get {
                return ResourceManager.GetString("AEEG_LowVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude-integrated electroencephalogram.
        /// </summary>
        public static string AEEGDesc {
            get {
                return ResourceManager.GetString("AEEGDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string Analysis {
            get {
                return ResourceManager.GetString("Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neonate Tracker.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to list.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        public static string Behavior {
            get {
                return ResourceManager.GetString("Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irregular.
        /// </summary>
        public static string Behavior_Irregular {
            get {
                return ResourceManager.GetString("Behavior_Irregular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response.
        /// </summary>
        public static string Behavior_NoResponse {
            get {
                return ResourceManager.GetString("Behavior_NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Behavior_Normal {
            get {
                return ResourceManager.GetString("Behavior_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convulsion.
        /// </summary>
        public static string Convulsion {
            get {
                return ResourceManager.GetString("Convulsion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cranial Nerves.
        /// </summary>
        public static string CranialNerves {
            get {
                return ResourceManager.GetString("CranialNerves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irregular activity.
        /// </summary>
        public static string CranialNerves_Irregular {
            get {
                return ResourceManager.GetString("CranialNerves_Irregular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string CranialNerves_Normal {
            get {
                return ResourceManager.GetString("CranialNerves_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new patient.
        /// </summary>
        public static string CreatePatient {
            get {
                return ResourceManager.GetString("CreatePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCLAIMER: This application is not affiliated in any way to the &quot;Servicio Andaluz de Salud&quot; or the &quot;Junta de Andalucía&quot;. The application is currently deployed in a development environment and there is no connection to any real system nor any use of real data..
        /// </summary>
        public static string DEBUG_Notice {
            get {
                return ResourceManager.GetString("DEBUG_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEG.
        /// </summary>
        public static string EEG {
            get {
                return ResourceManager.GetString("EEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low voltage.
        /// </summary>
        public static string EEG_LowVoltage {
            get {
                return ResourceManager.GetString("EEG_LowVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string EEG_Normal {
            get {
                return ResourceManager.GetString("EEG_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        public static string EEG_Slow {
            get {
                return ResourceManager.GetString("EEG_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electroencephalogram.
        /// </summary>
        public static string EEGDesc {
            get {
                return ResourceManager.GetString("EEGDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ErrorBack {
            get {
                return ResourceManager.GetString("ErrorBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application error has occurred..
        /// </summary>
        public static string ErrorDescription {
            get {
                return ResourceManager.GetString("ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of exams performed to the patient.
        /// </summary>
        public static string Examinations {
            get {
                return ResourceManager.GetString("Examinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply filter.
        /// </summary>
        public static string FilterApply {
            get {
                return ResourceManager.GetString("FilterApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean filter.
        /// </summary>
        public static string FilterClean {
            get {
                return ResourceManager.GetString("FilterClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fields marked with * are mandatory..
        /// </summary>
        public static string FormRequired {
            get {
                return ResourceManager.GetString("FormRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application for tracking neonates at risk of hypoxic ischemic encephalopathy..
        /// </summary>
        public static string HomeDescription1 {
            get {
                return ResourceManager.GetString("HomeDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the main page of the application. Now that you are authenticated you can go to the patients section to start working with the application..
        /// </summary>
        public static string HomeDescription2 {
            get {
                return ResourceManager.GetString("HomeDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypothermia.
        /// </summary>
        public static string Hypothermia {
            get {
                return ResourceManager.GetString("Hypothermia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List patients.
        /// </summary>
        public static string ListPatients {
            get {
                return ResourceManager.GetString("ListPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string Monitoring {
            get {
                return ResourceManager.GetString("Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NBR Surveillance.
        /// </summary>
        public static string NBRSurveillance {
            get {
                return ResourceManager.GetString("NBRSurveillance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient data.
        /// </summary>
        public static string PatientData {
            get {
                return ResourceManager.GetString("PatientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient details.
        /// </summary>
        public static string PatientDetails {
            get {
                return ResourceManager.GetString("PatientDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From the patients section you can list all the patients registered currently in the system, register new patients or inspect and modify the information of the patients..
        /// </summary>
        public static string PatientsSection {
            get {
                return ResourceManager.GetString("PatientsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        public static string Position_Bad {
            get {
                return ResourceManager.GetString("Position_Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string Position_Good {
            get {
                return ResourceManager.GetString("Position_Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irregular.
        /// </summary>
        public static string Position_Irregular {
            get {
                return ResourceManager.GetString("Position_Irregular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflexes.
        /// </summary>
        public static string Reflexes {
            get {
                return ResourceManager.GetString("Reflexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irregular.
        /// </summary>
        public static string Reflexes_Irregular {
            get {
                return ResourceManager.GetString("Reflexes_Irregular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reaction.
        /// </summary>
        public static string Reflexes_NoReaction {
            get {
                return ResourceManager.GetString("Reflexes_NoReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Reflexes_Normal {
            get {
                return ResourceManager.GetString("Reflexes_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not register so many users in such a short time..
        /// </summary>
        public static string RegistrationThrottleError {
            get {
                return ResourceManager.GetString("RegistrationThrottleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing results {0} through {1} from a total of {2}..
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time slot.
        /// </summary>
        public static string TimeSlot {
            get {
                return ResourceManager.GetString("TimeSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 hours.
        /// </summary>
        public static string TimeSlot_24h {
            get {
                return ResourceManager.GetString("TimeSlot_24h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 hours.
        /// </summary>
        public static string TimeSlot_48h {
            get {
                return ResourceManager.GetString("TimeSlot_48h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5-7 days.
        /// </summary>
        public static string TimeSlot_5_7d {
            get {
                return ResourceManager.GetString("TimeSlot_5_7d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;6 hours.
        /// </summary>
        public static string TimeSlot_6h {
            get {
                return ResourceManager.GetString("TimeSlot_6h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 72 hours.
        /// </summary>
        public static string TimeSlot_72h {
            get {
                return ResourceManager.GetString("TimeSlot_72h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharge.
        /// </summary>
        public static string TimeSlot_Discharge {
            get {
                return ResourceManager.GetString("TimeSlot_Discharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tone.
        /// </summary>
        public static string Tone {
            get {
                return ResourceManager.GetString("Tone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string Tone_Good {
            get {
                return ResourceManager.GetString("Tone_Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irregular.
        /// </summary>
        public static string Tone_Irregular {
            get {
                return ResourceManager.GetString("Tone_Irregular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Tone_Low {
            get {
                return ResourceManager.GetString("Tone_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be between {1} and {2}..
        /// </summary>
        public static string Validation_Range {
            get {
                return ResourceManager.GetString("Validation_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must have a length between {2} and {1} characters..
        /// </summary>
        public static string Validation_StringLength {
            get {
                return ResourceManager.GetString("Validation_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
