//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtTracker.Resources.NbrSurveillance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NtTracker.Resources.NbrSurveillance.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add time period.
        /// </summary>
        public static string AddSurveillance {
            get {
                return ResourceManager.GetString("AddSurveillance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Nervous System Exploration.
        /// </summary>
        public static string CnsExploration {
            get {
                return ResourceManager.GetString("CnsExploration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNS Explorations.
        /// </summary>
        public static string CnsExplorationsShort {
            get {
                return ResourceManager.GetString("CnsExplorationsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create period for NBR surveillance.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete period of time.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete surveillance.
        /// </summary>
        public static string DeleteNbrSurveillance {
            get {
                return ResourceManager.GetString("DeleteNbrSurveillance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This NBR surveillance will be irreversibly removed from the system. Are you sure you want to delete it?.
        /// </summary>
        public static string DeleteSurveillanceDescription {
            get {
                return ResourceManager.GetString("DeleteSurveillanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete confirmation.
        /// </summary>
        public static string DeleteSurveillanceTitle {
            get {
                return ResourceManager.GetString("DeleteSurveillanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of NBR Surveillance information of the patient for different periods of time. To add a new set of data for a new period of time, click the link on the tab (+ Add time period)..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit NBR surveillance.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already surveillance information for that time slot..
        /// </summary>
        public static string ErrorRepeated {
            get {
                return ResourceManager.GetString("ErrorRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tf Us.
        /// </summary>
        public static string TfUltrasound {
            get {
                return ResourceManager.GetString("TfUltrasound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfontanellar ultrasound.
        /// </summary>
        public static string TfUltrasoundDesc {
            get {
                return ResourceManager.GetString("TfUltrasoundDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base GG..
        /// </summary>
        public static string TfUs_BaseGG {
            get {
                return ResourceManager.GetString("TfUs_BaseGG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edema.
        /// </summary>
        public static string TfUs_Edema {
            get {
                return ResourceManager.GetString("TfUs_Edema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string TfUs_Normal {
            get {
                return ResourceManager.GetString("TfUs_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thalamus injury.
        /// </summary>
        public static string TfUs_ThalamusInjury {
            get {
                return ResourceManager.GetString("TfUs_ThalamusInjury", resourceCulture);
            }
        }
    }
}
