//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtTracker.Resources.Operation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NtTracker.Resources.Operation.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation data.
        /// </summary>
        public static string OperationData {
            get {
                return ResourceManager.GetString("OperationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string OperationPatient {
            get {
                return ResourceManager.GetString("OperationPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter operations.
        /// </summary>
        public static string OperationsFilter {
            get {
                return ResourceManager.GetString("OperationsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID.
        /// </summary>
        public static string OperationsPatientId {
            get {
                return ResourceManager.GetString("OperationsPatientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string OperationTime {
            get {
                return ResourceManager.GetString("OperationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp from.
        /// </summary>
        public static string OperationTimeFrom {
            get {
                return ResourceManager.GetString("OperationTimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string OperationTimeTo {
            get {
                return ResourceManager.GetString("OperationTimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation type.
        /// </summary>
        public static string OperationType {
            get {
                return ResourceManager.GetString("OperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string OperationUser {
            get {
                return ResourceManager.GetString("OperationUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account deleted.
        /// </summary>
        public static string Type_AccountDelete {
            get {
                return ResourceManager.GetString("Type_AccountDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account has been deleted by an administrator..
        /// </summary>
        public static string Type_AccountDelete_Desc {
            get {
                return ResourceManager.GetString("Type_AccountDelete_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account locked.
        /// </summary>
        public static string Type_AccountLock {
            get {
                return ResourceManager.GetString("Type_AccountLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user account has been locked due to repeated login failures..
        /// </summary>
        public static string Type_AccountLock_Desc {
            get {
                return ResourceManager.GetString("Type_AccountLock_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logged in.
        /// </summary>
        public static string Type_AccountLogin {
            get {
                return ResourceManager.GetString("Type_AccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user has logged in to the system..
        /// </summary>
        public static string Type_AccountLogin_Desc {
            get {
                return ResourceManager.GetString("Type_AccountLogin_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account locked manually.
        /// </summary>
        public static string Type_AccountManualLock {
            get {
                return ResourceManager.GetString("Type_AccountManualLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account has been locked by an administrator..
        /// </summary>
        public static string Type_AccountManualLock_Desc {
            get {
                return ResourceManager.GetString("Type_AccountManualLock_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account unlocked manually.
        /// </summary>
        public static string Type_AccountManualUnlock {
            get {
                return ResourceManager.GetString("Type_AccountManualUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account has been unlocked by an administrator..
        /// </summary>
        public static string Type_AccountManualUnlock_Desc {
            get {
                return ResourceManager.GetString("Type_AccountManualUnlock_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user registered.
        /// </summary>
        public static string Type_AccountRegister {
            get {
                return ResourceManager.GetString("Type_AccountRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered to the system..
        /// </summary>
        public static string Type_AccountRegister_Desc {
            get {
                return ResourceManager.GetString("Type_AccountRegister_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypothermia information created.
        /// </summary>
        public static string Type_HypothermiaCreate {
            get {
                return ResourceManager.GetString("Type_HypothermiaCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypothermia information for a time slot created..
        /// </summary>
        public static string Type_HypothermiaCreate_Desc {
            get {
                return ResourceManager.GetString("Type_HypothermiaCreate_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypothermia information deleted.
        /// </summary>
        public static string Type_HypothermiaDelete {
            get {
                return ResourceManager.GetString("Type_HypothermiaDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypothermia information for a time slot deleted..
        /// </summary>
        public static string Type_HypothermiaDelete_Desc {
            get {
                return ResourceManager.GetString("Type_HypothermiaDelete_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypothermia information modified.
        /// </summary>
        public static string Type_HypothermiaUpdate {
            get {
                return ResourceManager.GetString("Type_HypothermiaUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypothermia information for a time slot modified..
        /// </summary>
        public static string Type_HypothermiaUpdate_Desc {
            get {
                return ResourceManager.GetString("Type_HypothermiaUpdate_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring created.
        /// </summary>
        public static string Type_MonitoringCreate {
            get {
                return ResourceManager.GetString("Type_MonitoringCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A monitoring of a patient has been created..
        /// </summary>
        public static string Type_MonitoringCreate_Desc {
            get {
                return ResourceManager.GetString("Type_MonitoringCreate_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring deleted.
        /// </summary>
        public static string Type_MonitoringDelete {
            get {
                return ResourceManager.GetString("Type_MonitoringDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A monitoring of a patient has been deleted..
        /// </summary>
        public static string Type_MonitoringDelete_Desc {
            get {
                return ResourceManager.GetString("Type_MonitoringDelete_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring modified.
        /// </summary>
        public static string Type_MonitoringUpdate {
            get {
                return ResourceManager.GetString("Type_MonitoringUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring of a patient modified..
        /// </summary>
        public static string Type_MonitoringUpdate_Desc {
            get {
                return ResourceManager.GetString("Type_MonitoringUpdate_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NBR surveillance information created.
        /// </summary>
        public static string Type_NbrSurveillanceCreate {
            get {
                return ResourceManager.GetString("Type_NbrSurveillanceCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NBR surveillance information for a time slot created..
        /// </summary>
        public static string Type_NbrSurveillanceCreate_Desc {
            get {
                return ResourceManager.GetString("Type_NbrSurveillanceCreate_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NBR surveillance information deleted.
        /// </summary>
        public static string Type_NbrSurveillanceDelete {
            get {
                return ResourceManager.GetString("Type_NbrSurveillanceDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NBR surveillance information for a time slot deleted..
        /// </summary>
        public static string Type_NbrSurveillanceDelete_Desc {
            get {
                return ResourceManager.GetString("Type_NbrSurveillanceDelete_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NBR surveillance information modified.
        /// </summary>
        public static string Type_NbrSurveillanceUpdate {
            get {
                return ResourceManager.GetString("Type_NbrSurveillanceUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NBR surveillance information for a time slot modified..
        /// </summary>
        public static string Type_NbrSurveillanceUpdate_Desc {
            get {
                return ResourceManager.GetString("Type_NbrSurveillanceUpdate_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking closed.
        /// </summary>
        public static string Type_PatientClose {
            get {
                return ResourceManager.GetString("Type_PatientClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tracking of a patient has been closed..
        /// </summary>
        public static string Type_PatientClose_Desc {
            get {
                return ResourceManager.GetString("Type_PatientClose_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New patient registered.
        /// </summary>
        public static string Type_PatientCreate {
            get {
                return ResourceManager.GetString("Type_PatientCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new patient has been registered to the system..
        /// </summary>
        public static string Type_PatientCreate_Desc {
            get {
                return ResourceManager.GetString("Type_PatientCreate_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient deleted.
        /// </summary>
        public static string Type_PatientDelete {
            get {
                return ResourceManager.GetString("Type_PatientDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient information deleted from the system..
        /// </summary>
        public static string Type_PatientDelete_Desc {
            get {
                return ResourceManager.GetString("Type_PatientDelete_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking opened.
        /// </summary>
        public static string Type_PatientOpen {
            get {
                return ResourceManager.GetString("Type_PatientOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tracking of a patient has been reopened..
        /// </summary>
        public static string Type_PatientOpen_Desc {
            get {
                return ResourceManager.GetString("Type_PatientOpen_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient modified.
        /// </summary>
        public static string Type_PatientUpdate {
            get {
                return ResourceManager.GetString("Type_PatientUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient information modified..
        /// </summary>
        public static string Type_PatientUpdate_Desc {
            get {
                return ResourceManager.GetString("Type_PatientUpdate_Desc", resourceCulture);
            }
        }
    }
}
