//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtTracker.Resources.Hypothermia {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NtTracker.Resources.Hypothermia.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add time period.
        /// </summary>
        public static string AddHypothermia {
            get {
                return ResourceManager.GetString("AddHypothermia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerebral MRI.
        /// </summary>
        public static string CerebralResonance {
            get {
                return ResourceManager.GetString("CerebralResonance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerebral Magnetic Resonance Imaging.
        /// </summary>
        public static string CerebralResonanceDesc {
            get {
                return ResourceManager.GetString("CerebralResonanceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base GG..
        /// </summary>
        public static string CMRI_BaseGG {
            get {
                return ResourceManager.GetString("CMRI_BaseGG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerebral cortex injury.
        /// </summary>
        public static string CMRI_CerebralCortexInjury {
            get {
                return ResourceManager.GetString("CMRI_CerebralCortexInjury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corpus callosum injury.
        /// </summary>
        public static string CMRI_CorpusCallosumInjury {
            get {
                return ResourceManager.GetString("CMRI_CorpusCallosumInjury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string CMRI_Normal {
            get {
                return ResourceManager.GetString("CMRI_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thalamus injury.
        /// </summary>
        public static string CMRI_ThalamusInjury {
            get {
                return ResourceManager.GetString("CMRI_ThalamusInjury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Nervous System Exploration.
        /// </summary>
        public static string CnsExploration {
            get {
                return ResourceManager.GetString("CnsExploration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNS Us.
        /// </summary>
        public static string CnsUltrasound {
            get {
                return ResourceManager.GetString("CnsUltrasound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Nervous System Ultrasound.
        /// </summary>
        public static string CnsUltrasoundDesc {
            get {
                return ResourceManager.GetString("CnsUltrasoundDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base GG..
        /// </summary>
        public static string CnsUs_BaseGG {
            get {
                return ResourceManager.GetString("CnsUs_BaseGG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edema.
        /// </summary>
        public static string CnsUs_Edema {
            get {
                return ResourceManager.GetString("CnsUs_Edema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string CnsUs_Normal {
            get {
                return ResourceManager.GetString("CnsUs_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thalamus injury.
        /// </summary>
        public static string CnsUs_ThalamusInjury {
            get {
                return ResourceManager.GetString("CnsUs_ThalamusInjury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create period for hypothermia.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create hypothermia exam.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete period of time.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hypothermia information for this period of time will be irreversibly removed from the system. Are you sure you want to remove this period of time?.
        /// </summary>
        public static string DeleteDescription {
            get {
                return ResourceManager.GetString("DeleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete confirmation.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Hypothermia information of the patient for different periods of time. To add a new set of data for a new period of time, click the link on the tab (+ Add time period)..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit period of time.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit hypothermia exam.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already hypothermia information for that time slot..
        /// </summary>
        public static string ErrorRepeated {
            get {
                return ResourceManager.GetString("ErrorRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no hypothermia information registered. Click the link above to create information for a time slot..
        /// </summary>
        public static string NoHypothermias {
            get {
                return ResourceManager.GetString("NoHypothermias", resourceCulture);
            }
        }
    }
}
