//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtTracker.Resources.Patient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NtTracker.Resources.Patient.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative data.
        /// </summary>
        public static string AdministrativeData {
            get {
                return ResourceManager.GetString("AdministrativeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altered reflexes.
        /// </summary>
        public static string AlteredReflexes {
            get {
                return ResourceManager.GetString("AlteredReflexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altered suction.
        /// </summary>
        public static string AlteredSuction {
            get {
                return ResourceManager.GetString("AlteredSuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altered tone.
        /// </summary>
        public static string AlteredTone {
            get {
                return ResourceManager.GetString("AlteredTone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apgar.
        /// </summary>
        public static string Apgar {
            get {
                return ResourceManager.GetString("Apgar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date from.
        /// </summary>
        public static string BirthDateFrom {
            get {
                return ResourceManager.GetString("BirthDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string BirthDateTo {
            get {
                return ResourceManager.GetString("BirthDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth type.
        /// </summary>
        public static string BirthType {
            get {
                return ResourceManager.GetString("BirthType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cesarean.
        /// </summary>
        public static string BirthType_Cesarean {
            get {
                return ResourceManager.GetString("BirthType_Cesarean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eutocic.
        /// </summary>
        public static string BirthType_Eutocic {
            get {
                return ResourceManager.GetString("BirthType_Eutocic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forceps.
        /// </summary>
        public static string BirthType_Forceps {
            get {
                return ResourceManager.GetString("BirthType_Forceps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatulas.
        /// </summary>
        public static string BirthType_Spatulas {
            get {
                return ResourceManager.GetString("BirthType_Spatulas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventouse.
        /// </summary>
        public static string BirthType_Ventouse {
            get {
                return ResourceManager.GetString("BirthType_Ventouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string ChangeHistory {
            get {
                return ResourceManager.GetString("ChangeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tracking for this patient will be closed and the status of the patient will no longer be taken into account by the system. This should be done if the patient no longer needs to be tracked by this application because he was either dicharged or any other reason. .
        /// </summary>
        public static string CloseDescription {
            get {
                return ResourceManager.GetString("CloseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can open again this tracking at any time. Are you sure you want to close the tracking of this patient?.
        /// </summary>
        public static string CloseDescription2 {
            get {
                return ResourceManager.GetString("CloseDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tracking confirmation.
        /// </summary>
        public static string CloseTitle {
            get {
                return ResourceManager.GetString("CloseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File patient.
        /// </summary>
        public static string CloseTracking {
            get {
                return ResourceManager.GetString("CloseTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coma.
        /// </summary>
        public static string Coma {
            get {
                return ResourceManager.GetString("Coma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altered state of consciousness.
        /// </summary>
        public static string ConciousnessData {
            get {
                return ResourceManager.GetString("ConciousnessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR Type.
        /// </summary>
        public static string CprType {
            get {
                return ResourceManager.GetString("CprType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type 1.
        /// </summary>
        public static string CprType_1 {
            get {
                return ResourceManager.GetString("CprType_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type 2.
        /// </summary>
        public static string CprType_2 {
            get {
                return ResourceManager.GetString("CprType_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type 3.
        /// </summary>
        public static string CprType_3 {
            get {
                return ResourceManager.GetString("CprType_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type 4.
        /// </summary>
        public static string CprType_4 {
            get {
                return ResourceManager.GetString("CprType_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type 5.
        /// </summary>
        public static string CprType_5 {
            get {
                return ResourceManager.GetString("CprType_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the information related to this patient will be irreversibly removed from the system. Are you sure you want to delete this patient?.
        /// </summary>
        public static string DeleteDescription {
            get {
                return ResourceManager.GetString("DeleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete patient.
        /// </summary>
        public static string DeletePatient {
            get {
                return ResourceManager.GetString("DeletePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete confirmation.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit patient.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit patient data.
        /// </summary>
        public static string EditPatientData {
            get {
                return ResourceManager.GetString("EditPatientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export results to spreadsheet.
        /// </summary>
        public static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string ExportedFileName {
            get {
                return ResourceManager.GetString("ExportedFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating spreadsheet... .
        /// </summary>
        public static string ExportInfo {
            get {
                return ResourceManager.GetString("ExportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: There is a limit to the amount of patients to export at once. If you reach this limit modify the filter to obtain an smaller result set..
        /// </summary>
        public static string ExportInfo2 {
            get {
                return ResourceManager.GetString("ExportInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter patients.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking number.
        /// </summary>
        public static string IdDesc {
            get {
                return ResourceManager.GetString("IdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last status.
        /// </summary>
        public static string LastStatus {
            get {
                return ResourceManager.GetString("LastStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of the patient at the time of filing..
        /// </summary>
        public static string LastStatusDesc {
            get {
                return ResourceManager.GetString("LastStatusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lethargy.
        /// </summary>
        public static string Lethargy {
            get {
                return ResourceManager.GetString("Lethargy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHC.
        /// </summary>
        public static string Nhc {
            get {
                return ResourceManager.GetString("Nhc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic History Number.
        /// </summary>
        public static string NhcDesc {
            get {
                return ResourceManager.GetString("NhcDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUHSA.
        /// </summary>
        public static string Nuhsa {
            get {
                return ResourceManager.GetString("Nuhsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andalusia Unique Health History Number.
        /// </summary>
        public static string NuhsaDesc {
            get {
                return ResourceManager.GetString("NuhsaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tracking for this patient will be open again and the status of the patient will be taken into account by the system again. Are you sure you want to open the tracking of this patient?.
        /// </summary>
        public static string OpenDescription {
            get {
                return ResourceManager.GetString("OpenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen tracking confirmation.
        /// </summary>
        public static string OpenTitle {
            get {
                return ResourceManager.GetString("OpenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen tracking.
        /// </summary>
        public static string OpenTracking {
            get {
                return ResourceManager.GetString("OpenTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other data.
        /// </summary>
        public static string OtherData {
            get {
                return ResourceManager.GetString("OtherData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string PatientSex {
            get {
                return ResourceManager.GetString("PatientSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string PatientSex_Female {
            get {
                return ResourceManager.GetString("PatientSex_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string PatientSex_Male {
            get {
                return ResourceManager.GetString("PatientSex_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient status.
        /// </summary>
        public static string PatientStatus {
            get {
                return ResourceManager.GetString("PatientStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filed.
        /// </summary>
        public static string PatientStatus_Closed {
            get {
                return ResourceManager.GetString("PatientStatus_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This patient&apos;s tracking is closed and has to be opened to be modified..
        /// </summary>
        public static string PatientStatus_ClosedDesc {
            get {
                return ResourceManager.GetString("PatientStatus_ClosedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypothermia.
        /// </summary>
        public static string PatientStatus_Hypothermia {
            get {
                return ResourceManager.GetString("PatientStatus_Hypothermia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient shows signs of moderate/severe HIE. Check the Hypothermia section..
        /// </summary>
        public static string PatientStatus_HypothermiaDesc {
            get {
                return ResourceManager.GetString("PatientStatus_HypothermiaDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string PatientStatus_Monitoring {
            get {
                return ResourceManager.GetString("PatientStatus_Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient shows signs of mild HIE. Check the Monitoring section..
        /// </summary>
        public static string PatientStatus_MonitoringDesc {
            get {
                return ResourceManager.GetString("PatientStatus_MonitoringDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NBR Surveillance.
        /// </summary>
        public static string PatientStatus_NbrSurveillance {
            get {
                return ResourceManager.GetString("PatientStatus_NbrSurveillance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient passes the NBR criteria. Check the NBR Surveillance section..
        /// </summary>
        public static string PatientStatus_NbrSurveillanceDesc {
            get {
                return ResourceManager.GetString("PatientStatus_NbrSurveillanceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string PatientStatus_Normal {
            get {
                return ResourceManager.GetString("PatientStatus_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient is in a good state or not enough info has been introduced yet..
        /// </summary>
        public static string PatientStatus_NormalDesc {
            get {
                return ResourceManager.GetString("PatientStatus_NormalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perinatal data.
        /// </summary>
        public static string PerinatalData {
            get {
                return ResourceManager.GetString("PerinatalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        public static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pH.
        /// </summary>
        public static string Ph {
            get {
                return ResourceManager.GetString("Ph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrant.
        /// </summary>
        public static string RegistrantName {
            get {
                return ResourceManager.GetString("RegistrantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stupor.
        /// </summary>
        public static string Stupor {
            get {
                return ResourceManager.GetString("Stupor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surnames.
        /// </summary>
        public static string Surnames {
            get {
                return ResourceManager.GetString("Surnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
