//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtTracker.Resources.Analysis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NtTracker.Resources.Analysis.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alanine transaminase (ALT/ALAT).
        /// </summary>
        public static string ALT {
            get {
                return ResourceManager.GetString("ALT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value outside of normal range..
        /// </summary>
        public static string ALTDanger {
            get {
                return ResourceManager.GetString("ALTDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal range is between 4.8 and 21.
        /// </summary>
        public static string ALTInfo {
            get {
                return ResourceManager.GetString("ALTInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspartate transaminase (AST/ASAT).
        /// </summary>
        public static string AST {
            get {
                return ResourceManager.GetString("AST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value outside of normal range..
        /// </summary>
        public static string ASTDanger {
            get {
                return ResourceManager.GetString("ASTDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal range is between 6 and 60.
        /// </summary>
        public static string ASTInfo {
            get {
                return ResourceManager.GetString("ASTInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chloride (Cl).
        /// </summary>
        public static string Chloride {
            get {
                return ResourceManager.GetString("Chloride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value outside of normal range..
        /// </summary>
        public static string ChlorideDanger {
            get {
                return ResourceManager.GetString("ChlorideDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal range is between 95 and 110.
        /// </summary>
        public static string ChlorideInfo {
            get {
                return ResourceManager.GetString("ChlorideInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatine kinase (CK/CPK).
        /// </summary>
        public static string CPK {
            get {
                return ResourceManager.GetString("CPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value outside of normal range..
        /// </summary>
        public static string CPKDanger {
            get {
                return ResourceManager.GetString("CPKDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal range is between 9.6 and 320.
        /// </summary>
        public static string CPKInfo {
            get {
                return ResourceManager.GetString("CPKInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hematocrit (Hct).
        /// </summary>
        public static string Hematocrit {
            get {
                return ResourceManager.GetString("Hematocrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage outside of normal range..
        /// </summary>
        public static string HematocritDanger {
            get {
                return ResourceManager.GetString("HematocritDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal range is between 0.31 and 0.63.
        /// </summary>
        public static string HematocritInfo {
            get {
                return ResourceManager.GetString("HematocritInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemoglobin (Hb).
        /// </summary>
        public static string Hemoglobin {
            get {
                return ResourceManager.GetString("Hemoglobin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value outside of normal range..
        /// </summary>
        public static string HemoglobinDanger {
            get {
                return ResourceManager.GetString("HemoglobinDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal range is between 140 and 200.
        /// </summary>
        public static string HemoglobinInfo {
            get {
                return ResourceManager.GetString("HemoglobinInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platelet count.
        /// </summary>
        public static string PlateletCount {
            get {
                return ResourceManager.GetString("PlateletCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal range is between 100 000 and 350 000.
        /// </summary>
        public static string PlateletCountInfo {
            get {
                return ResourceManager.GetString("PlateletCountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count outside of normal range, possible presence of Thrombocytopenia..
        /// </summary>
        public static string PlateletDanger {
            get {
                return ResourceManager.GetString("PlateletDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potassium (K).
        /// </summary>
        public static string Potassium {
            get {
                return ResourceManager.GetString("Potassium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value outside of normal range, possible presence of hypokalemia or hyperkalemia..
        /// </summary>
        public static string PotassiumDanger {
            get {
                return ResourceManager.GetString("PotassiumDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal range is between 3.5 and 5.9.
        /// </summary>
        public static string PotassiumInfo {
            get {
                return ResourceManager.GetString("PotassiumInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total protein.
        /// </summary>
        public static string Proteins {
            get {
                return ResourceManager.GetString("Proteins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value outside of normal range..
        /// </summary>
        public static string ProteinsDanger {
            get {
                return ResourceManager.GetString("ProteinsDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal range is between 60 and 84.
        /// </summary>
        public static string ProteinsInfo {
            get {
                return ResourceManager.GetString("ProteinsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sodium (Na).
        /// </summary>
        public static string Sodium {
            get {
                return ResourceManager.GetString("Sodium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value outside of normal range..
        /// </summary>
        public static string SodiumDanger {
            get {
                return ResourceManager.GetString("SodiumDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal range is between 134 and 147.
        /// </summary>
        public static string SodiumInfo {
            get {
                return ResourceManager.GetString("SodiumInfo", resourceCulture);
            }
        }
    }
}
