//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtTracker.Resources.Monitoring {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NtTracker.Resources.Monitoring.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add exam.
        /// </summary>
        public static string AddMonitoring {
            get {
                return ResourceManager.GetString("AddMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ataxia.
        /// </summary>
        public static string Ataxia {
            get {
                return ResourceManager.GetString("Ataxia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditory sensory deficit.
        /// </summary>
        public static string AuditoryDeficit {
            get {
                return ResourceManager.GetString("AuditoryDeficit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deafness.
        /// </summary>
        public static string AuditoryDeficit_Deafness {
            get {
                return ResourceManager.GetString("AuditoryDeficit_Deafness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypoacusia.
        /// </summary>
        public static string AuditoryDeficit_Hypoacusia {
            get {
                return ResourceManager.GetString("AuditoryDeficit_Hypoacusia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string AuditoryDeficit_No {
            get {
                return ResourceManager.GetString("AuditoryDeficit_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response to contact with caretaker.
        /// </summary>
        public static string CaretakerResponse {
            get {
                return ResourceManager.GetString("CaretakerResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognitive.
        /// </summary>
        public static string CognitiveData {
            get {
                return ResourceManager.GetString("CognitiveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognitive deficit.
        /// </summary>
        public static string CognitiveDeficit {
            get {
                return ResourceManager.GetString("CognitiveDeficit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep.
        /// </summary>
        public static string CognitiveDeficit_Deep {
            get {
                return ResourceManager.GetString("CognitiveDeficit_Deep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mild.
        /// </summary>
        public static string CognitiveDeficit_Mild {
            get {
                return ResourceManager.GetString("CognitiveDeficit_Mild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate.
        /// </summary>
        public static string CognitiveDeficit_Moderate {
            get {
                return ResourceManager.GetString("CognitiveDeficit_Moderate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CognitiveDeficit_No {
            get {
                return ResourceManager.GetString("CognitiveDeficit_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe.
        /// </summary>
        public static string CognitiveDeficit_Severe {
            get {
                return ResourceManager.GetString("CognitiveDeficit_Severe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create monitoring.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteMonitoring {
            get {
                return ResourceManager.GetString("DeleteMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This exam will be irreversibly removed from the system. Are you sure you want to delete it?.
        /// </summary>
        public static string DeleteMonitoringDescription {
            get {
                return ResourceManager.GetString("DeleteMonitoringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete confirmation.
        /// </summary>
        public static string DeleteMonitoringTitle {
            get {
                return ResourceManager.GetString("DeleteMonitoringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development reflexes.
        /// </summary>
        public static string DevelopmentReflexes {
            get {
                return ResourceManager.GetString("DevelopmentReflexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        public static string DevelopmentReflexes_Absent {
            get {
                return ResourceManager.GetString("DevelopmentReflexes_Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme.
        /// </summary>
        public static string DevelopmentReflexes_Extreme {
            get {
                return ResourceManager.GetString("DevelopmentReflexes_Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        public static string DevelopmentReflexes_Present {
            get {
                return ResourceManager.GetString("DevelopmentReflexes_Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dyskinesia.
        /// </summary>
        public static string Dyskinesia {
            get {
                return ResourceManager.GetString("Dyskinesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dystonia.
        /// </summary>
        public static string Dystonia {
            get {
                return ResourceManager.GetString("Dystonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit monitoring exam.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotional.
        /// </summary>
        public static string EmotionalData {
            get {
                return ResourceManager.GetString("EmotionalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displeasure.
        /// </summary>
        public static string EmotionalResponse_Displeasure {
            get {
                return ResourceManager.GetString("EmotionalResponse_Displeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string EmotionalResponse_None {
            get {
                return ResourceManager.GetString("EmotionalResponse_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleasure.
        /// </summary>
        public static string EmotionalResponse_Pleasure {
            get {
                return ResourceManager.GetString("EmotionalResponse_Pleasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperreflexia.
        /// </summary>
        public static string Hyperreflexia {
            get {
                return ResourceManager.GetString("Hyperreflexia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam info.
        /// </summary>
        public static string MonitoringInfo {
            get {
                return ResourceManager.GetString("MonitoringInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor.
        /// </summary>
        public static string MotorData {
            get {
                return ResourceManager.GetString("MotorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muscular tone.
        /// </summary>
        public static string MuscularTone {
            get {
                return ResourceManager.GetString("MuscularTone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string MuscularTone_Both {
            get {
                return ResourceManager.GetString("MuscularTone_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypertonia.
        /// </summary>
        public static string MuscularTone_Hypertonia {
            get {
                return ResourceManager.GetString("MuscularTone_Hypertonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypotonia.
        /// </summary>
        public static string MuscularTone_Hypotonia {
            get {
                return ResourceManager.GetString("MuscularTone_Hypotonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string MuscularTone_Normal {
            get {
                return ResourceManager.GetString("MuscularTone_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No exams have been saved for this patient. Click the button below to add a new one..
        /// </summary>
        public static string NoMonitorings {
            get {
                return ResourceManager.GetString("NoMonitorings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimaryReflexes.
        /// </summary>
        public static string PrimaryReflexes {
            get {
                return ResourceManager.GetString("PrimaryReflexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smiles.
        /// </summary>
        public static string Smiles {
            get {
                return ResourceManager.GetString("Smiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response to sound stimuli.
        /// </summary>
        public static string SoundResponse {
            get {
                return ResourceManager.GetString("SoundResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spasticity.
        /// </summary>
        public static string Spasticity {
            get {
                return ResourceManager.GetString("Spasticity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response to contact with strangers.
        /// </summary>
        public static string StrangersResponse {
            get {
                return ResourceManager.GetString("StrangersResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response to tactile stimuli.
        /// </summary>
        public static string TactileResponse {
            get {
                return ResourceManager.GetString("TactileResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring exam details.
        /// </summary>
        public static string ViewTitle {
            get {
                return ResourceManager.GetString("ViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual sensory deficit.
        /// </summary>
        public static string VisualDeficit {
            get {
                return ResourceManager.GetString("VisualDeficit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blindness.
        /// </summary>
        public static string VisualDeficit_Blindness {
            get {
                return ResourceManager.GetString("VisualDeficit_Blindness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease.
        /// </summary>
        public static string VisualDeficit_Decrease {
            get {
                return ResourceManager.GetString("VisualDeficit_Decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string VisualDeficit_No {
            get {
                return ResourceManager.GetString("VisualDeficit_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocal deficit.
        /// </summary>
        public static string VocalDeficit {
            get {
                return ResourceManager.GetString("VocalDeficit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Babbling.
        /// </summary>
        public static string VocalDeficit_Babbling {
            get {
                return ResourceManager.GetString("VocalDeficit_Babbling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string VocalDeficit_No {
            get {
                return ResourceManager.GetString("VocalDeficit_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snarl.
        /// </summary>
        public static string VocalDeficit_Snarl {
            get {
                return ResourceManager.GetString("VocalDeficit_Snarl", resourceCulture);
            }
        }
    }
}
